version: '3.7'

networks:
  prometheus:

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    internet-exporter:
        image: chriscmsoft/internet-watcher:latest
        build:
          context: .
        ports:
        - 8005:8005
        networks:
        - prometheus
        restart: always
    prometheus:
        image: prom/prometheus:v2.1.0
        volumes:
        - ./prometheus/:/etc/prometheus/
        - prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
        - 9090:9090
        networks:
        - prometheus
        restart: always
    grafana:
        image: grafana/grafana
        user: "472"
        ports:
        - 3000:3000
        volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
        - ./grafana/config.monitoring
        networks:
        - prometheus
        restart: always